import type { MigrationInterface, QueryRunner } from "typeorm";

export class InitialDistributionsSchema00001 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    // Note: In a real environment, this can be auto-generated by TypeORM.
    // These tables match the DistributionBatch and ClaimAction entities.
    await queryRunner.query(`
      CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

      DO $$ BEGIN
        CREATE TYPE "distribution_batch_status_enum" AS ENUM ('ACTIVE', 'PAUSED', 'COMPLETED', 'CANCELLED');
      EXCEPTION
        WHEN duplicate_object THEN null;
      END $$;

      CREATE TABLE "distribution_batch" (
        "id" varchar PRIMARY KEY NOT NULL,
        "contractId" varchar NOT NULL,
        "distributor" varchar NOT NULL,
        "token" varchar NOT NULL,
        "totalAmount" bigint NOT NULL,
        "claimedAmount" bigint NOT NULL DEFAULT '0',
        "recipientCount" integer NOT NULL,
        "status" "distribution_batch_status_enum" NOT NULL DEFAULT 'ACTIVE',
        "pausedAt" varchar,
        "resumedAt" varchar,
        "statusLedger" integer,
        "uniqueRef" varchar NOT NULL,
        "ledgerNumber" integer NOT NULL,
        "txHash" varchar NOT NULL,
        "createdAt" TIMESTAMP NOT NULL DEFAULT now(),
        "updatedAt" TIMESTAMP NOT NULL DEFAULT now(),
        CONSTRAINT "uq_distribution_batch_unique_ref" UNIQUE ("uniqueRef")
      );
      CREATE INDEX "IDX_distribution_batch_contractId" ON "distribution_batch" ("contractId");
      CREATE INDEX "IDX_distribution_batch_distributor" ON "distribution_batch" ("distributor");

      CREATE TABLE "distribution_claim_action" (
        "id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
        "batchId" varchar NOT NULL,
        "claimant" varchar NOT NULL,
        "amount" bigint NOT NULL,
        "txHash" varchar NOT NULL,
        "ledgerNumber" integer NOT NULL,
        "eventIndex" integer NOT NULL,
        "eventTimestamp" varchar NOT NULL,
        "createdAt" TIMESTAMP NOT NULL DEFAULT now(),
        CONSTRAINT "FK_claim_batch" FOREIGN KEY ("batchId") REFERENCES "distribution_batch"("id") ON DELETE CASCADE,
        CONSTRAINT "uq_claim_event_identity" UNIQUE ("txHash", "ledgerNumber", "eventIndex")
      );
      CREATE INDEX "IDX_claim_batchId" ON "distribution_claim_action" ("batchId");
      CREATE INDEX "IDX_claim_claimant" ON "distribution_claim_action" ("claimant");
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE "distribution_claim_action"`);
    await queryRunner.query(`DROP TABLE "distribution_batch"`);
    await queryRunner.query(`DROP TYPE "distribution_batch_status_enum"`);
  }
}
