import {
	type MigrationInterface,
	type QueryRunner,
	Table,
	TableIndex,
} from "typeorm";

export class InitialStreamsSchema00001 implements MigrationInterface {
	public async up(queryRunner: QueryRunner): Promise<void> {
		// Note: In a real environment, this can be auto-generated by TypeORM
		// These tables match the Stream, WithdrawalAction, and CancelAction entities.
		await queryRunner.query(`
      CREATE TABLE "stream" (
        "id" varchar PRIMARY KEY NOT NULL,
        "sender" varchar NOT NULL,
        "recipient" varchar NOT NULL,
        "token" varchar NOT NULL,
        "totalAmount" bigint NOT NULL,
        "startTime" bigint NOT NULL,
        "endTime" bigint NOT NULL,
        "amountWithdrawn" bigint NOT NULL DEFAULT '0',
        "canceled" boolean NOT NULL DEFAULT false,
        "createdAt" TIMESTAMP NOT NULL DEFAULT now(),
        "updatedAt" TIMESTAMP NOT NULL DEFAULT now()
      );

      CREATE TABLE "stream_withdrawal_action" (
        "id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
        "streamId" varchar NOT NULL,
        "recipient" varchar NOT NULL,
        "amount" bigint NOT NULL,
        "txHash" varchar NOT NULL,
        "timestamp" bigint NOT NULL,
        "createdAt" TIMESTAMP NOT NULL DEFAULT now(),
        CONSTRAINT "FK_withdrawal_stream" FOREIGN KEY ("streamId") REFERENCES "stream"("id") ON DELETE CASCADE
      );
      CREATE INDEX "IDX_withdrawal_streamId" ON "stream_withdrawal_action" ("streamId");

      CREATE TABLE "stream_cancel_action" (
        "id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
        "streamId" varchar NOT NULL,
        "canceler" varchar NOT NULL,
        "txHash" varchar NOT NULL,
        "timestamp" bigint NOT NULL,
        "createdAt" TIMESTAMP NOT NULL DEFAULT now(),
        CONSTRAINT "FK_cancel_stream" FOREIGN KEY ("streamId") REFERENCES "stream"("id") ON DELETE CASCADE
      );
      CREATE INDEX "IDX_cancel_streamId" ON "stream_cancel_action" ("streamId");
    `);
	}

	public async down(queryRunner: QueryRunner): Promise<void> {
		await queryRunner.query(`DROP TABLE "stream_cancel_action"`);
		await queryRunner.query(`DROP TABLE "stream_withdrawal_action"`);
		await queryRunner.query(`DROP TABLE "stream"`);
	}
}
